// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAS3vSMUjELEK5CjQl-MAikzxEuxDydeYE',
    appId: '1:244433959703:web:2c73add23a32a2a73b9552',
    messagingSenderId: '244433959703',
    projectId: 'glasses-fe0ac',
    authDomain: 'glasses-fe0ac.firebaseapp.com',
    storageBucket: 'glasses-fe0ac.appspot.com',
    measurementId: 'G-NCGTT8RK15',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKiOAlmEc1_8UBho2urMGTM1pgaPs-wp4',
    appId: '1:244433959703:android:1333d2ca2900232b3b9552',
    messagingSenderId: '244433959703',
    projectId: 'glasses-fe0ac',
    storageBucket: 'glasses-fe0ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfmQ_fmeSuVukB6-4QjLvV3tz44yME4rs',
    appId: '1:244433959703:ios:c66b5182e2c77fa63b9552',
    messagingSenderId: '244433959703',
    projectId: 'glasses-fe0ac',
    storageBucket: 'glasses-fe0ac.appspot.com',
    iosBundleId: 'com.example.glassar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfmQ_fmeSuVukB6-4QjLvV3tz44yME4rs',
    appId: '1:244433959703:ios:5827ac2894ed4d813b9552',
    messagingSenderId: '244433959703',
    projectId: 'glasses-fe0ac',
    storageBucket: 'glasses-fe0ac.appspot.com',
    iosBundleId: 'com.example.glassar.RunnerTests',
  );
}
